kind: source
spec:
  name: "tarot-cards"
  registry: "grpc"
  path: "localhost:7777"
  tables: ['*']
  destinations: ["sqlite"]
  spec:
    randomness_seed: 42
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: "v2.4.11"
  spec:
    connection_string: ./db.sqlite